# Config file for automatic testing at travis-ci.org

dist: xenial
language: python
arch:
  - amd64
  - arm64
before_install:
  - sudo apt-get install -y git wget
python:
  - "2.7"
  - "3.7"
env:
  global:
    - SUDO=""

install:
  - if [[ "${TRAVIS_CPU_ARCH}" == "arm64" ]]; then
      wget -q "https://github.com/Archiconda/build-tools/releases/download/0.2.3/Archiconda3-0.2.3-Linux-aarch64.sh" -O archiconda.sh
      chmod +x archiconda.sh;
      export CONDA_ALWAYS_YES=1;
      ./archiconda.sh create -p $HOME/miniconda python=$TRAVIS_PYTHON_VERSION conda conda-build pytest six pytest-cov pytest-mock;
    else
      wget https://repo.anaconda.com/pkgs/misc/conda-execs/conda-4.7.5-linux-64.exe -O conda.exe
      chmod +x conda.exe;
      export CONDA_ALWAYS_YES=1;
      ./conda.exe create -p $HOME/miniconda python=$TRAVIS_PYTHON_VERSION conda conda-build pytest six pytest-cov pytest-mock;
    fi
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      conda install futures;
    fi
  - conda build conda.recipe --no-test
  - $SUDO conda install --use-local conda-package-handling
  - $SUDO conda info -a
script:
  # rebuilding the recipe with our new CPH installed tests it a bit deeper than the test suite.
  - sudo conda build conda.recipe
  - sudo pytest -v --color=yes --cov=conda_package_handling tests
after_success:
  - sudo conda install codecov
  - codecov
